### ISSUE TITLE
disconnect stream.setTimeout

### ISSUE THREAD

**Issue by flyinprogrammer** [slate/slate-irc#35]
I'm new to javascript - so pardon my idiocracy - but I think we might have a bug?

I'm trying to run `npm install && npm test` within this project and I'm getting the following error snippet for all of the tests:

```bash
  1) away() on RPL_AWAY should emit "away":
     TypeError: stream.setTimeout is not a function
      at lib/plugins/disconnect.js:18:12
      at Client.use (index.js:376:3)
      at new Client (index.js:60:8)
      at Client (index.js:52:41)
      at Context.<anonymous> (test/away.js:8:20)
```

https://github.com/slate/slate-irc/blob/master/lib/plugins/disconnect.js#L18

It would seem that `stream` doesn't have the `setTimeout()` method?

![debug](https://www.evernote.com/shard/s9/sh/14def16c-c85d-4f05-8388-03157b646de5/b4841bba164b4cfe/res/eb179c06-42a9-46db-ba73-c86f674537cd/skitch.png)

Getting rid of that 1 line seems to fix things, but I barely know enough javascript to understand the consequences of that decision. 

Am I doing something wrong?

**Comment by flyinprogrammer** [comment]
Ah.

I think I figured this out. In the case of this code getting used downstream, you're probably using a 
[net.Socket](https://nodejs.org/api/net.html#net_class_net_socket) which has a [setTimeout](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback) method. But in the case of our tests we use a [stream.Passthrough](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) which has no such method.

I'm going to close this and go open a PR to fix this once I figure out how people fix this haha.
